version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: article_db
    restart: always
    networks: 
      - backend
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "artDB", "-U", "dev" ]
      timeout: 45s
      interval: 10s
      retries: 5

  api:
      image: article
      build:
        context: .
      restart: on-failure:2
      networks:
        - backend
      ports:
        - "8080:8080"
      depends_on:
        postgres:
          condition: service_healthy

volumes:
  db_data:

networks:
  backend:
    driver: bridge
